### ISSUE TITLE
Anchor for the footer using the entire container

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/waifuland-fe#33]
![Example](https://cdn.discordapp.com/attachments/1035255667352666203/1036110450343022602/unknown.png)

Github button is using the entire flex container which is causing that you can click anywhere in the footer.

**Comment by chechdebug** [comment]
I can help you with that 👯‍♀️

**Comment by jd-apprentice** [comment]
- [x] Fixed on #34
